---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: e2e-tests
  name: e2e-tests

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-chrome
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '0 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-chrome
          labels:
            jobgroup: e2e-chrome
        spec:
          containers:
            - name: e2e-chrome
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
              command:
                - /bin/sh
                - -c
                - |
                  export CI_BUILD_ID=$(echo $(cat /etc/podinfo/labels | grep -oP 'job-name="\K[^"]+'))
                  CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser chrome --record --key secret_key --parallel --ci-build-id $CI_BUILD_ID
              volumeMounts:
                - name: podinfo
                  mountPath: /etc/podinfo
                  readOnly: true
          volumes:
            - name: podinfo
              downwardAPI:
                items:
                  - path: "labels"
                    fieldRef:
                      fieldPath: metadata.labels
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-firefox
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '10 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-firefox
          labels:
            jobgroup: e2e-firefox
        spec:
          containers:
            - name: e2e-firefox
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
              command:
                - /bin/sh
                - -c
                - |
                  export CI_BUILD_ID=$(echo $(cat /etc/podinfo/labels | grep -oP 'job-name="\K[^"]+'))
                  CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser firefox --record --key secret_key --parallel --ci-build-id $CI_BUILD_ID
              volumeMounts:
                - name: podinfo
                  mountPath: /etc/podinfo
                  readOnly: true
          volumes:
            - name: podinfo
              downwardAPI:
                items:
                  - path: "labels"
                    fieldRef:
                      fieldPath: metadata.labels
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-electron
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '20 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-electron
          labels:
            jobgroup: e2e-electron
        spec:
          containers:
            - name: e2e-electron
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
              command:
                - /bin/sh
                - -c
                - |
                  export CI_BUILD_ID=$(echo $(cat /etc/podinfo/labels | grep -oP 'job-name="\K[^"]+'))
                  CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser electron --record --key secret_key --parallel --ci-build-id $CI_BUILD_ID
              volumeMounts:
                - name: podinfo
                  mountPath: /etc/podinfo
                  readOnly: true
          volumes:
            - name: podinfo
              downwardAPI:
                items:
                  - path: "labels"
                    fieldRef:
                      fieldPath: metadata.labels
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-edge
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '30 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-edge
          labels:
            jobgroup: e2e-edge
        spec:
          containers:
            - name: e2e-edge
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
              command:
                - /bin/sh
                - -c
                - |
                  export CI_BUILD_ID=$(echo $(cat /etc/podinfo/labels | grep -oP 'job-name="\K[^"]+'))
                  CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser edge --record --key secret_key --parallel --ci-build-id $CI_BUILD_ID
              volumeMounts:
                - name: podinfo
                  mountPath: /etc/podinfo
                  readOnly: true
          volumes:
            - name: podinfo
              downwardAPI:
                items:
                  - path: "labels"
                    fieldRef:
                      fieldPath: metadata.labels
          restartPolicy: Never
status: {}