# Install Cypress, then run all tests (in parallel)
stages:
  - build
  - test

# Set environment variables for folders in "cache" job settings for npm modules and Cypress binary
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# Cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

# Install NPM dependencies and Cypress
install:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: build
  script:
    - npm ci

e2e tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  # parallel: 5
  script:
    # install dependencies
    - npm ci
    - npx cypress run --env ENV=qa
