---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: e2e-tests
  name: e2e-tests

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-chrome
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '0 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-chrome
          labels:
            jobgroup: e2e-chrome
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser chrome --record --key secret_key --parallel --ci-build-id chrome_`date +%Y-%m-%d_%R`
              name: e2e-chrome
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-firefox
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '10 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-firefox
          labels:
            jobgroup: e2e-firefox
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser firefox --record --key secret_key --parallel --ci-build-id firefox_`date +%Y-%m-%d_%R`
              name: e2e-firefox
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-electron
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '20 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-electron
          labels:
            jobgroup: e2e-electron
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser electron --record --key secret_key --parallel --ci-build-id electron_`date +%Y-%m-%d_%R`
              name: e2e-electron
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
          restartPolicy: Never
status: {}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    jobgroup: e2e-tests
  name: scheduled-e2e-edge
  namespace: e2e-tests
spec:
  timeZone: Europe/Belgrade
  schedule: '30 9 * * *'
  jobTemplate:
    spec:
      parallelism: 2
      activeDeadlineSeconds: 1800
      template:
        metadata:
          name: scheduled-e2e-edge
          labels:
            jobgroup: e2e-edge
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - CURRENTS_API_URL='http://director.sorry-cypress:1234' npx cypress-cloud run --env ENV=kube --browser edge --record --key secret_key --parallel --ci-build-id edge_`date +%Y-%m-%d_%R`
              name: e2e-edge
              image: e2e:latest
              imagePullPolicy: Never
              resources: {}
          restartPolicy: Never
status: {}