version: '3.7'
services:
  # Sorry Cypress Minio Docker Compose from https://github.com/sorry-cypress/sorry-cypress repository
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'sorry-cypress'
      MONGO_INITDB_ROOT_PASSWORD: 'cypress-sorry'
    ports:
      - 27017:27017
    networks:
      - e2e-tests

  director:
    image: agoldis/sorry-cypress-director:latest
    environment:
      ALLOWED_KEYS: 'secret_key'
      DASHBOARD_URL: http://kube.local:8080
      INACTIVITY_TIMEOUT_SECONDS: 600
      EXECUTION_DRIVER: '../execution/mongo/driver'
      MONGODB_URI: 'mongodb://sorry-cypress:cypress-sorry@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      SCREENSHOTS_DRIVER: '../screenshots/minio.driver'
      GITLAB_JOB_RETRIES: 'false'
      MINIO_ACCESS_KEY: 'sorry-cypress'
      MINIO_SECRET_KEY: 'cypress-sorry'
      MINIO_ENDPOINT: 'storage' # Director must be able to access minio service within your network configuration using MINIO_ENDPOINT and MINIO_PORT
      MINIO_URL: 'http://storage'
      MINIO_PORT: '9000'
      MINIO_USESSL: 'false'
      MINIO_BUCKET: sorry-cypress
      PROBE_LOGGER: 'false'
    ports:
      - 1234:1234
    depends_on:
      - mongo
    networks:
      - e2e-tests

  api:
    image: agoldis/sorry-cypress-api:latest
    environment:
      MONGODB_URI: 'mongodb://sorry-cypress:cypress-sorry@mongo:27017'
      MONGODB_DATABASE: 'sorry-cypress'
      APOLLO_PLAYGROUND: 'false'
    ports:
      - 4000:4000
    depends_on:
      - mongo
    networks:
      - e2e-tests

  dashboard:
    image: agoldis/sorry-cypress-dashboard:latest
    environment:
      GRAPHQL_SCHEMA_URL: http://kube.local:4000
      GRAPHQL_CLIENT_CREDENTIALS: ''
      PORT: 8080
      CI_URL: ''
    ports:
      - 8080:8080
    depends_on:
      - mongo
      - api
    networks:
      - e2e-tests

  storage:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: 'sorry-cypress'
      MINIO_ROOT_PASSWORD: 'cypress-sorry'
    command: minio server --console-address ':9090' /data
    ports:
      - 9000:9000
      - 9090:9090
    networks:
      - e2e-tests

  createbuckets:
    image: minio/mc
    network_mode: service:storage
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c '
      sleep 3;
      /usr/bin/mc config host add myminio http://localhost:9000 sorry-cypress cypress-sorry;
      /usr/bin/mc rm -r --dangerous --force myminio/sorry-cypress;
      /usr/bin/mc mb myminio/sorry-cypress;
      /usr/bin/mc anonymous set download myminio/sorry-cypress;
      /usr/bin/mc anonymous set public myminio/sorry-cypress;
      exit 0;
      '

networks:
  e2e-tests:
    name: e2e-tests
    driver: bridge
