version: '3.7'
services:
  # Restful Booker Platform Docker Compose from https://github.com/mwinteringham/restful-booker-platform repository
  rbp-booking:
    image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
    ports:
      - 3000:3000
    restart: always
    networks:
      - e2e-tests

  rbp-room:
    image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
    ports:
      - 3001:3001
    restart: always
    networks:
      - e2e-tests

  rbp-branding:
    image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
    ports:
      - 3002:3002
    restart: always
    networks:
      - e2e-tests

  rbp-assets:
    image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
    ports:
      - 3003:3003
    restart: always
    networks:
      - e2e-tests

  rbp-auth:
    image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
    ports:
      - 3004:3004
    restart: always
    networks:
      - e2e-tests

  rbp-report:
    image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
    ports:
      - 3005:3005
    restart: always
    networks:
      - e2e-tests

  rbp-message:
    image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
    ports:
      - 3006:3006
    restart: always
    networks:
      - e2e-tests

  rbp-proxy:
    image: mwinteringham/restfulbookerplatform_proxy:latest
    ports:
      - 80:80
    restart: always
    networks:
      - e2e-tests

networks:
  e2e-tests:
    name: e2e-tests
    driver: bridge
