name: Manual Run All E2E Tests on Restful Booker Platform

on:
  workflow_dispatch:

jobs:
  run-all-e2e-tests:
    name: Run All E2E Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          env: ENV=prod
      # after the test run completes store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
      # Test run videos are always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
      # Test run reports are always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports
          path: cypress/reports
          retention-days: 5