name: Manual Run All E2E Tests with Sorry-Cypress

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run Tests'
        required: true
        default: 'prod'
        type: choice
        options:
        - prod
        - local
      browser:
        description: 'Browser in which to run Tests'
        required: true
        default: 'electron'
        type: choice
        options:
        - electron
        - chrome

env:
  CYPRESS_DIRECTOR_URL: ${{ secrets.CYPRESS_DIRECTOR_URL }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ inputs.browser }}-${{ github.run_id }}

jobs:
  install-dependencies:
    name: Install Dependencies with cache
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci

  run-all-cypress-tests:
    name: Run All E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [install-dependencies]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: execute-tests
        name: Execute Cypress Tests
        run: npm run cy2:ci:run -- --env ENV=${{ inputs.environment }} --browser ${{ inputs.browser }} --headless