name: Nightly Cypress Tests

on:
 
    //schedule:
    - cron: '0 3 * * *'  # Her gece 1:35'te çalıştır
    workflow_dispatch:   # Manuel başlatma için workflow_dispatch event'i ekleniyor

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm run test

      - name: Notify test results to Slack
        if: ${{ always() }}  # Her durumda çalıştırılsın
        run: |
          if [ ${{ job.status }} == 'success' ]; then
              curl -X POST -H 'Content-type: application/json' --data '{"text":"The Tests tests have passed %100! Please click on file:///C:/Users/AEN/Desktop/Gitproject/opt7.com-cypress/cypress/reports/html/cucumber-report.html for the results. "}' $SLACK_WEBHOOK_URL
          else
              curl -X POST -H 'Content-type: application/json' --data '{"text":"The tests have failed. Please click on file:///C:/Users/AEN/Desktop/Gitproject/opt7.com-cypress/cypress/reports/html/cucumber-report.html for the results."}' $SLACK_WEBHOOK_URL
              # Ek olarak, test raporunu Slack'e göndermek için cypress-multi-reporters gibi bir eklenti kullanabilirsiniz.
          fi
        env:
          //SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
