name: Nightly Cypress Tests

on:
 
    schedule:
    - cron: '0 3 * * *'  # Her gece 1:35'te çalıştır
    workflow_dispatch:   # Manuel başlatma için workflow_dispatch event'i ekleniyor

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm run test

      - name: Notify test results to Slack
        if: ${{ always() }}  # Her durumda çalıştırılsın
        run: |
         if [ ${{ job.status }} == 'success' ]; then
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Cypress testleri başarıyla tamamlandı!"}' $SLACK_WEBHOOK_URL
         else
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Cypress testleri başarısız oldu!"}' $SLACK_WEBHOOK_URL
         fi
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
