name: Run All E2E Tests in parallel

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run Tests'
        required: true
        default: 'local'
        type: choice
        options:
        - local
        - prod
      skip-bugs:
        description: 'Skip Test with Known Bugs'
        required: true
        default: true
        type: boolean

jobs:
  start-rbp-and-run-all-e2e-tests:
    if: ${{ inputs.environment == 'local' }}
    name: Tests on local - ${{ matrix.browser }} - ${{ matrix.runnerIndex }} of ${{ matrix.runnerTotal }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
    env:
      CI: 1
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, electron, firefox, edge]
        runnerIndex: [0, 1]
        runnerTotal: [2]
    services:
        rbp-booking:
          image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
          ports:
            - 3000:3000
        rbp-room:
          image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
          ports:
            - 3001:3001
        rbp-branding:
          image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
          ports:
            - 3002:3002
        rbp-assets:
          image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
          ports:
            - 3003:3003
        rbp-auth:
          image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
          ports:
            - 3004:3004
        rbp-report:
          image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
          ports:
            - 3005:3005
        rbp-message:
          image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
          ports:
            - 3006:3006
        rbp-proxy:
          image: mwinteringham/restfulbookerplatform_proxy:latest
          ports:
            - 80:80
    steps:
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
      - id: install-dependencies
        name: Install Dependencies
        run: npm install
      - id: install-cypress
        name: Install Cypress
        run: ./node_modules/.bin/cypress install
      - id: execute-tests
        if: ${{ inputs.skip-bugs }}
        name: Execute Cypress Tests
        run: npx cypress run --record --env ENV=${{ inputs.environment }},TAGS='not @bug' --browser ${{ matrix.browser }}
        env:
          CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ matrix.browser }}-${{ github.run_id }}
          SPLIT: ${{ matrix.runnerTotal }} 
          SPLIT_INDEX: ${{ matrix.runnerIndex }}
      - id: execute-tests-bugs
        if: ${{ !inputs.skip-bugs }}
        name: Execute Cypress Tests (incl. tests with known bugs)
        run: npx cypress run --env ENV=${{ inputs.environment }} --browser ${{ matrix.browser }}
        env:
          CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ matrix.browser }}-${{ github.run_id }}
          SPLIT: ${{ matrix.runnerTotal }} 
          SPLIT_INDEX: ${{ matrix.runnerIndex }}
      - id: upload-screenshots
        name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/screenshots
          retention-days: 5
      - id: upload-videos
        name: Upload Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/videos
          retention-days: 5
      - id: upload-reports
        name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/reports
          retention-days: 5

  run-all-e2e-tests:
    if: ${{ inputs.environment == 'prod' }}
    name: Tests on prod - ${{ matrix.browser }} - ${{ matrix.runnerIndex }} of ${{ matrix.runnerTotal }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: cypress/browsers:node-18.16.0-chrome-113.0.5672.92-1-ff-113.0-edge-113.0.1774.35-1
    env:
      CI: 1
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, electron, firefox, edge]
        runnerIndex: [0, 1]
        runnerTotal: [2]
    steps:
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
      - id: install-dependencies
        name: Install Dependencies
        run: npm install
      - id: install-cypress
        name: Install Cypress
        run: ./node_modules/.bin/cypress install
      - id: execute-tests
        if: ${{ inputs.skip-bugs }}
        name: Execute Cypress Tests
        run: npx cypress run --record --env ENV=${{ inputs.environment }},TAGS='not @bug' --browser ${{ matrix.browser }}
        env:
          CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ matrix.browser }}-${{ github.run_id }}
          SPLIT: ${{ matrix.runnerTotal }} 
          SPLIT_INDEX: ${{ matrix.runnerIndex }}
      - id: execute-tests-bugs
        if: ${{ !inputs.skip-bugs }}
        name: Execute Cypress Tests (incl. tests with known bugs)
        run: npx cypress run --env ENV=${{ inputs.environment }} --browser ${{ matrix.browser }}
        env:
          CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ matrix.browser }}-${{ github.run_id }}
          SPLIT: ${{ matrix.runnerTotal }} 
          SPLIT_INDEX: ${{ matrix.runnerIndex }}
      - id: upload-screenshots
        name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/screenshots
          retention-days: 5
      - id: upload-videos
        name: Upload Videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/videos
          retention-days: 5
      - id: upload-reports
        name: Upload Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-reports-(${{ matrix.browser }}-${{ matrix.runnerIndex }}-of-${{ matrix.runnerTotal }})
          path: cypress/reports
          retention-days: 5