name: Run All E2E Tests with Sorry-Cypress

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run Tests'
        required: true
        default: 'prod'
        type: choice
        options:
        - local
        - prod
      browser:
        description: 'Browser in which to run Tests'
        required: true
        default: 'electron'
        type: choice
        options:
        - electron
        - chrome

env:
  CYPRESS_DIRECTOR_URL: ${{ secrets.CYPRESS_DIRECTOR_URL }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_CI_BUILD_ID: ${{ inputs.environment }}-${{ inputs.browser }}-${{ github.run_id }}

jobs:
  install-dependencies:
    name: Install Dependencies with cache
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      CI: 1
    steps:
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - id: cache-node
        name: Cache Node
        uses: actions/cache@v3
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - id: install-dependencies
        name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm install

  start-rbp-and-run-all-e2e-tests:
    if: ${{ inputs.environment == 'local' }}
    name: Start Restful Booker Platform and Run All E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [install-dependencies]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    services:
        rbp-booking:
          image: mwinteringham/restfulbookerplatform_booking:1.6.24c7b22
          ports:
            - 3000:3000
        rbp-room:
          image: mwinteringham/restfulbookerplatform_room:1.6.24c7b22
          ports:
            - 3001:3001
        rbp-branding:
          image: mwinteringham/restfulbookerplatform_branding:1.6.24c7b22
          ports:
            - 3002:3002
        rbp-assets:
          image: mwinteringham/restfulbookerplatform_assets:1.6.24c7b22
          ports:
            - 3003:3003
        rbp-auth:
          image: mwinteringham/restfulbookerplatform_auth:1.6.24c7b22
          ports:
            - 3004:3004
        rbp-report:
          image: mwinteringham/restfulbookerplatform_report:1.6.24c7b22
          ports:
            - 3005:3005
        rbp-message:
          image: mwinteringham/restfulbookerplatform_message:1.6.24c7b22
          ports:
            - 3006:3006
        rbp-proxy:
          image: mwinteringham/restfulbookerplatform_proxy:latest
          ports:
            - 80:80
    steps:
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - id: cache-node
        name: Cache Node
        uses: actions/cache@v3
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - id: install-cypress
        name: Install Cypress
        run: ./node_modules/.bin/cypress install
      - id: execute-tests
        name: Execute Cypress Tests
        run: npm run cy2:ci:run -- --env ENV=${{ inputs.environment }} --browser ${{ inputs.browser }} --headless

  run-all-cypress-tests:
    if: ${{ inputs.environment == 'prod' }}
    name: Run All E2E Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: [install-dependencies]
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - id: cache-node
        name: Cache Node
        uses: actions/cache@v3
        env:
          cache-name: cache-node
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - id: install-cypress
        name: Install Cypress
        run: ./node_modules/.bin/cypress install
      - id: execute-tests
        name: Execute Cypress Tests
        run: npm run cy2:ci:run -- --env ENV=${{ inputs.environment }} --browser ${{ inputs.browser }} --headless